feat: add option to start on Monday (#18)
nhn/tui.date-picker pull request #70
Opened 2021-03-04 07:43 UTC by lja1018

* 한 주의 시작을 월요일로 지정할 수 있는 옵션 `startOnMonday`을 추가하였습니다.

2021-03-05 00:59 UTC, jung-han commented
메신저에서 말씀드린대로 월요일에 한정짓기 보다는 인덱스를 받아서 처리하는게 나을 수도 있을 것 같습니다.

* https://bootstrap-datepicker.readthedocs.io/en/latest/options.html?highlight=start#weekstart
* https://api.jqueryui.com/datepicker/#option-firstDay

다른 라이브러리 참고 부탁드립니다!

2021-03-08 07:46 UTC, jung-han commented on src/js/calendar/index.js
> + *     @param {boolean} [options.weekStart = 0] - Day of the week start. 0 (Sunday) to 6 (Saturday) (default: 0(start on Sunday))
당시에 협의했을때는 Mon, Tue, ...형태로 진행되는 것으로 알았는데 숫자로 한 이유가 있을까요?

2021-03-08 07:47 UTC, lja1018 commented on src/js/calendar/index.js
> + *     @param {boolean} [options.weekStart = 0] - Day of the week start. 0 (Sunday) to 6 (Saturday) (default: 0(start on Sunday))
아 그때 팀장님께서 고민하고 답 달라고 하셔서 숫자 인덱스 형태로 진행하는걸로 결정했습니다!

2021-03-08 07:47 UTC, jung-han commented on src/js/calendar/layerBody/date.js
>  var TYPE_DATE = require('../../constants').TYPE_DATE;
datepicker나 rangePicker는 weekStart옵션이 적용되지 않고 있습니다. 같이 개발이 되어야 할 것 같습니다.

2021-03-08 07:49 UTC, jung-han commented on src/js/calendar/index.js
> + *     @param {boolean} [options.weekStart = 0] - Day of the week start. 0 (Sunday) to 6 (Saturday) (default: 0(start on Sunday))
음...그럼 Mon, Tue 형태보다 인덱스 기준이 사용자가 쓰기 더 편할것 같다는 의견이신거죠?

2021-03-08 07:51 UTC, jung-han commented on src/js/calendar/layerBody/date.js
>  var TYPE_DATE = require('../../constants').TYPE_DATE;
테스트, 예제 코드 또한 필요할 것 같습니다.

2021-03-08 07:52 UTC, jung-han requested changes
동작 안되는 부분이랑 예제 코드, 테스트 추가 부탁드릴게요

2021-03-09 01:23 UTC, lja1018 commented on src/js/calendar/index.js
> + *     @param {boolean} [options.weekStart = 0] - Day of the week start. 0 (Sunday) to 6 (Saturday) (default: 0(start on Sunday))
넵 맞습니다!

2021-03-10 07:47 UTC, lja1018 commented on src/js/calendar/layerBody/date.js
>  var TYPE_DATE = require('../../constants').TYPE_DATE;
`DatePicker` 옵션으로 이동했습니다.

2021-03-11 07:40 UTC, seonim-ryu commented on src/js/calendar/body.js
> +      this._dateLayer = new DateLayer(language, option);
`language` 값이 `option`의 값이라서 `weekStart`를 개별로 넘기던지 `options`를 통째로 넘겨주던지 하는게 좋겠습니다~
```js
new DateLayer(language, option.weekStart);
```

그리고 우리 컨벤션이 옵션 변수명은 `options`로 사용하기로 해서 이참에 같이 수정되면 좋겠네요ㅎ

2021-03-11 07:42 UTC, seonim-ryu commented on src/js/calendar/index.js
> + *     @param {boolean} [options.weekStart = 0] - Day of the week start. 0 (Sunday) to 6 (Saturday) (default: 0(start on Sunday))
옵션값을 숫자로 사용할지 문자로 사용할지가.. 이거 때문이었군요ㅎ
저도 숫자값보다는 문자열 사용이 사용자 입장에서 덜 헷갈릴거 같고 기왕이면 옵션 값이 대소문자 같이 했을 때 내부에서 소문자로 변환해서 사용할 수 있도록 처리되면 좋겠네요~
> `Mon` (외부 옵션 입력값) -> `mon` (내부 처리값)

2021-03-11 07:44 UTC, seonim-ryu commented on src/js/calendar/index.js
> +          weekStart: 0
만약 문자열로 옵션 값이 변경된다면 옵션명을 `weekStartDay`로 변경하는건 어떠신가요??

2021-03-11 07:55 UTC, seonim-ryu commented on src/js/calendar/layerBody/date.js
>        for (; weekNumber < weeksCount; weekNumber += 1) {
이건 `for`보다 `while`문을 사용하면 더 깔끔할것 같네요~

2021-03-11 07:55 UTC, js87zz commented on test/calendar/body.spec.js
> +      body.destroy();
이런 코드는 setup 함수에 작성하는 것이 좋을 것 같습니다.

2021-03-11 07:56 UTC, js87zz commented on test/calendar/body.spec.js
> +      expect(body._dateLayer._makeContext().Sun).toBe(day);
검증하려는 내용이 내부 프로퍼티에 너무 깊숙히 접근하는대요. 이 방법외에는 다른 방법이 없나요?
테스트든 어플리케이션 코드는 구현에 지나치게 종속적인 코드는 결합도면에서 좋지 않을 것 같습니다~

2021-03-11 07:58 UTC, js87zz commented on src/js/calendar/layerBody/date.js
>        for (; weekNumber < weeksCount; weekNumber += 1) {
개인적으로는 `while`문이 더 가독성에 좋을 것 같다는 생각이 드네요..ㅎㅎ

2021-03-11 08:02 UTC, seonim-ryu commented on src/js/calendar/layerBody/date.js
> +          firstWeek = this._getWeek(year, month, firstWeekDates);
이건 함수로 분리할 수 있겠네요~ 그러면 위에서 주석으로 처리한 부분도 함수 네이밍으로 대체되겠군요

2021-03-11 08:08 UTC, seonim-ryu commented on src/js/calendar/layerBody/date.js
> +    _isFirstWeek: function(weekNumber, dayInMonth) {
컨벤션이 바꼈는데 정말 설명이 길게 필요한 경우가 아니라면 프라이빗 메서드에서는 jsdoc을 작성하지 않아도 됩니다~
파라미터명만 봐도 충분히 알 수 있을듯요
그리고 `weekNumber`는 나중에 타입이 바뀔거 같지만.. 그렇지 않다면 `weekDayIndex`로 파라미터명을 사용하는건 어떨까요??

2021-03-11 08:17 UTC, seonim-ryu commented on test/calendar/body.spec.js
> +      body = new Body(container, { language: 'en', weekStart: index });
매번 인스턴스를 생성하고 인스턴스 옵션으로 날짜가 변경되는지 테스트하는 것보다
`body.changeWeekStartDay()` 메서드를 하나 추가해서 해당 메서드를 호출할 때마다 변경되었는지 비교하는게 낫지 않을까요??
퍼블릭 메서드가 좀 그렇다면 프라이빗 메서드로 선언해도 좋고요~

2021-03-11 08:24 UTC, seonim-ryu approved these changes
리뷰 완료합니다~ `for`문이 3번 연속으로 실행되는 함수가 있는데 속도도 한 번 체크해주시면 좋을 것 같습니다! 고생하셨어요~

2021-03-11 08:45 UTC, shiren approved these changes
수고하셨어요.
수정되면 다시 볼게요

2021-03-11 08:45 UTC, shiren commented on src/js/calendar/index.js
> + *     @param {boolean} [options.weekStart = 0] - Day of the week start. 0 (Sunday) to 6 (Saturday) (default: 0(start on Sunday))
외부에는 문자로 받고 내부에서는 그냥 숫자를 사용하면 될 것 같습니다.
그리고 내부에서는 숫자를 바로 사용하지 말고 enum 역할을 하는 상수 객체를 사용하면 되겠네요.

2021-03-11 23:19 UTC, jung-han commented on src/js/calendar/index.js
> + *     @param {boolean} [options.weekStart = 0] - Day of the week start. 0 (Sunday) to 6 (Saturday) (default: 0(start on Sunday))
Mon, mon 다 입력되게 해도 되겠네요

2021-03-11 23:21 UTC, jung-han approved these changes
완료입니다. 다른 분들이 이미 리뷰를 다 해주셨네요. 고생하셨습니다~

2021-03-16 06:31 UTC, lja1018 commented on test/calendar/body.spec.js
> +      body = new Body(container, { language: 'en', weekStart: index });
`dateLayer` 테스트를 따로 작성했습니다!

2021-03-16 06:31 UTC, lja1018 commented on test/calendar/body.spec.js
> +      expect(body._dateLayer._makeContext().Sun).toBe(day);
`dateLayer` 테스트를 따로 작성해서 깊숙히 접근하지 않게 바꿨습니다~!

2021-03-17 07:54 UTC, seonim-ryu commented on src/js/dateRangePicker/index.js
> + *         @param {string} [options.endpicker.weekStartDay = 'Sun'] - Start of the week. 'Sun', 'Mon', ..., 'Sat'(default: 'Sun'(start on Sunday))
레인지 피커에서는 `startpicker `, `endpicker`에 `weekStartDay` 옵션이 각각 설정되는데 공통 옵션을 받아서 처리하는건 어떨까요?? (레인지 피커에서 시작 요일을 캘린더마다 다르게 설정할 일은 없을 것 같아서요)

```js
var picker = tui.DatePicker.createRangePicker({
      startpicker: {
         // ...
      },
      endpicker: {
          // ...
      },
      weekStartDay: 'Sun'
  });
```

2021-03-17 07:59 UTC, dongsik-yoo reviewed
리뷰 완료합니다. 수고하셨습니다.

2021-03-17 07:59 UTC, dongsik-yoo commented on src/js/calendar/layerBody/date.js
> +    _isFirstWeek: function(weekIndex, dayInMonth) {
this에 접근하지 않는 판별함수는 클래스 밖에 두고 써도 되겠어요. 재사용이 많을 함수로 보입니다. 참고 부탁드려요.

2021-03-17 07:59 UTC, dongsik-yoo commented on src/js/dateRangePicker/index.js
> +        weekStartDay: options.startpicker.weekStartDay || 'Sun'
디폴트 값을 변수로 선언하면 변경하기 편하지 않을까요?

2021-03-17 08:00 UTC, seonim-ryu approved these changes
리뷰 완료합니다. 이건 팁인데 처음 리뷰를 받고 추가 작업을 하는 경우 별도 PR로 분리하거나 특정 해시 커밋으로 리뷰를 요청하면 리뷰를 더 쾌적하게 할 수 있습니다ㅎㅎ 고생하셨어요!

2021-03-17 08:10 UTC, jung-han commented on src/js/calendar/layerBody/date.js
> +};
사용자에게 받는 옵션이 아닌경우에는 이 맵을 기준으로 전부 사용하는 것은 어떤가요?
타입스크립트가 아니다보니 문자열을 기준으로 매번 코드를 짜다보면 오타를 알아채기 힘들것 같습니다

2021-03-17 08:10 UTC, jung-han approved these changes
완료입니다~

2021-03-17 08:24 UTC, dotaitch approved these changes
[3/17] 리뷰 완료했습니다.

2021-03-17 08:24 UTC, dotaitch commented on src/js/calendar/index.js
> + *     @param {string} [options.weekStartDay = 'Sun'] - Start of the week. 'Sun', 'Mon', ..., 'Sat'(default: 'Sun'(start on Sunday))
number도 받으면 좋을 것 같습니다!

2021-03-17 08:24 UTC, dotaitch commented on src/js/dateRangePicker/index.js
> +        weekStartDay: options.startpicker.weekStartDay || 'Sun'
`weekStartDay`에 값이 없으면 `new DatePicker` 할 때 디폴트값인 `'Sun'`이 들어가지 않나요?? 맞다면 불필요한 처리인 것 같습니다.

2021-03-18 02:11 UTC, lja1018 commented on src/js/dateRangePicker/index.js
> + *         @param {string} [options.endpicker.weekStartDay = 'Sun'] - Start of the week. 'Sun', 'Mon', ..., 'Sat'(default: 'Sun'(start on Sunday))
자유롭게 두 레인지 피커를 따로 설정하도록 유지하겠습니다. 혹시라도 그런 니즈가 있을 수 있으니까요 ㅋㅋ

2021-03-18 02:26 UTC, lja1018 commented on src/js/calendar/index.js
> + *     @param {string} [options.weekStartDay = 'Sun'] - Start of the week. 'Sun', 'Mon', ..., 'Sat'(default: 'Sun'(start on Sunday))
기존에 number (인덱스) 형태의 옵션에서 문자열로 변경한거라 이대로 유지하겠습니다!

2021-03-18 03:15 UTC, merged